version: '3.8'

services:
  app:
    container_name: nlip_pwa
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start
    restart: unless-stopped
